basePath: /
definitions:
  domain.ProxyRequest:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  domain.ProxyResponse:
    properties:
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      id:
        type: string
      length:
        type: integer
      status:
        type: integer
    type: object
  domain.StoredRequestResponse:
    properties:
      request:
        $ref: '#/definitions/domain.ProxyRequest'
      response:
        $ref: '#/definitions/domain.ProxyResponse'
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This server handles incoming HTTP requests from clients, forwards them
    to external services, and returns the result to the client in JSON format.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Proxy Server API
  version: 1.22.4
paths:
  /proxy:
    post:
      consumes:
      - application/json
      description: This endpoint handles HTTP requests from clients
      parameters:
      - description: proxy request
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.ProxyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ProxyResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Status Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Proxy HTTP requests
      tags:
      - requests
  /stored:
    get:
      description: Returns a list of stored proxy requests and responses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.StoredRequestResponse'
            type: array
      summary: Get Stored Requests
      tags:
      - requests
swagger: "2.0"
